src/src/Models/PriceCommodity.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace src.Models
{
    public class PriceCommodity
    {
        public Guid priceCommodityId { get; set; }
        //[Required]
        [Display(Name = "Time")]
        public DateTime time { get; set; }
        //[Required]

        [Display(Name = "Commodity Date")]
        public DateTime commodityDate { get; set; }

        public string enteredBy { get; set; }

        [Required]
        [Display(Name = "Commodity")]
        public string commodity { get; set; }

        [Required]
        [Display(Name = "Class Variety")]
        public string classVariety { get; set; }

        [Required]
        public double? priceLow { get; set; }

        [Required]
        public double? priceHigh { get; set; }

        public double? averageLow { get; set; }

        public double? averageHigh { get; set; }

        public double? average { get; set; }

        [Required]
        public int totalDays { get; set; }

        [Display(Name = "Commodity Remarks")]
        public string commodityRemarks { get; set; }

        [NotMapped]
        public IList<SelectListItem> commodityList { get; set; }

        public int? ControlNumber { get; set; }

        //[Display(Name = "Ticket Type")]
        //public Enum.TicketType ticketType { get; set; }
        //[Display(Name = "Ticket Priority")]
        //public Enum.TicketPriority ticketPriority { get; set; }
        //[Display(Name = "Destination")]
        //public Enum.TicketChannel ticketChannel { get; set; }

        //public Guid organizationId { get; set; }
        //public Organization organization { get; set; }

    }
}

src/src/Controllers/Api/PriceCommodityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using src.Data;
using src.Models;
using src.Services;

namespace src.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/PriceCommodity")]
    //[Authorize]
    public class PriceCommodityController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDotnetdesk _dotnetdesk;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;

        public PriceCommodityController(ApplicationDbContext context,
            IDotnetdesk dotnetdesk,
            UserManager<ApplicationUser> userManager,
            IEmailSender emailSender)
        {
            _context = context;
            _dotnetdesk = dotnetdesk;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        // GET: api/PriceCommodity
        [HttpGet("{organizationId}")]
        public IActionResult GetPriceCommodity([FromRoute]Guid organizationId)
        {
            var commodities = _context.Commodities.ToList();
            return Json(new { data = commodities });
        }

        // GET: api/PriceCommodity
        [HttpGet("GetPrice")]
        public IActionResult GetPrice([FromRoute]Guid organizationId)
        {
            var price = _context.PriceCommodity.ToList();
            return Json(new { data = price });
        }

        // POST: api/SupportEngineer
        [HttpPost]
        public async Task<IActionResult> PostPriceCommodity([FromBody] JObject model)
        {
            Guid objGuid = Guid.Empty;
            var info = await _userManager.GetUserAsync(User);
            var averageLow = _context.PriceCommodity.Where(x => x.commodityDate.Day == DateTime.Now.Day && x.commodity == model["commodity"].ToString() && x.classVariety == model["classVariety"].ToString()).Select(x => x.priceLow).Sum();
            var averageHigh = _context.PriceCommodity.Where(x => x.commodityDate.Day == DateTime.Now.Day && x.commodity == model["commodity"].ToString() && x.classVariety == model["classVariety"].ToString()).Select(x => x.priceHigh).Sum();
            objGuid = Guid.Parse(model["priceCommodityId"].ToString());
            var getLastControlNumber = _context.PriceCommodity.OrderByDescending(x => x.ControlNumber).Select(x => x.ControlNumber).FirstOrDefault();

            if (objGuid == Guid.Empty)
            {
                PriceCommodity priceCommodity = new PriceCommodity
                {
                    //time = Convert.ToDateTime(model["time"].ToString()),
                    commodityDate = DateTime.Now,
                    commodity = model["commodity"].ToString(),
                    commodityRemarks = model["commodityRemarks"].ToString(),
                    priceLow = Convert.ToDouble(model["priceLow"].ToString()),
                    priceHigh = Convert.ToDouble(model["priceHigh"].ToString()),
                    classVariety = model["classVariety"].ToString()
                };
                priceCommodity.enteredBy = info.FullName;
                priceCommodity.average = (priceCommodity.priceLow + priceCommodity.priceHigh) / 2;

                if (getLastControlNumber == null)
                {
                    priceCommodity.ControlNumber = 1;
                }
                else
                {
                    priceCommodity.ControlNumber = getLastControlNumber.Value + 1;
                }

                var currentTotalDays = _context.PriceCommodity.OrderByDescending(x => x.commodityDate).Where(x => x.commodity == model["commodity"].ToString() && x.classVariety == model["classVariety"].ToString()).Select(x => x.totalDays).FirstOrDefault();
                var countDays = _context.PriceCommodity.Where(x => x.commodity == model["commodity"].ToString() && x.classVariety == model["classVariety"].ToString()).Count();
                var monthChecker = _context.PriceCommodity.OrderByDescending(x => x.commodityDate).Where(x => x.commodity == model["commodity"].ToString() && x.classVariety == model["classVariety"].ToString()).Select(x => x.commodityDate).FirstOrDefault();
                var latestMonth = monthChecker.Month;
                if (currentTotalDays == 0)
                {
                    priceCommodity.totalDays = 1;
                    priceCommodity.averageLow = priceCommodity.priceLow / priceCommodity.totalDays;
                    priceCommodity.averageHigh = priceCommodity.priceHigh / priceCommodity.totalDays;
                }
                else if (DateTime.Now.Month == latestMonth)
                {
                    priceCommodity.totalDays = countDays + 1;
                    priceCommodity.averageLow = (priceCommodity.priceLow + averageLow) / priceCommodity.totalDays;
                    priceCommodity.averageHigh = (priceCommodity.priceHigh + averageHigh) / priceCommodity.totalDays;
                }
                else
                {
                    priceCommodity.totalDays = 1;
                    priceCommodity.averageLow = priceCommodity.priceLow / priceCommodity.totalDays;
                    priceCommodity.averageHigh = priceCommodity.priceHigh / priceCommodity.totalDays;
                }

                priceCommodity.priceCommodityId = Guid.NewGuid();
                _context.PriceCommodity.Add(priceCommodity);
            }
            else
            {
                var currentPrice = _context.PriceCommodity.Where(x => x.priceCommodityId == objGuid).FirstOrDefault();
                if (currentPrice.priceLow != Convert.ToInt32(model["priceLow"].ToString()) || currentPrice.priceHigh != Convert.ToInt32(model["priceHigh"].ToString()) || currentPrice.commodityRemarks != model["commodityRemarks"].ToString())
                {
                    var one = "";
                    var two = "";
                    var three = "";
                    if (currentPrice.priceLow != Convert.ToInt32(model["priceLow"].ToString()))
                    {
                        one = "Price (Low) = " + currentPrice.priceLow + " - " + model["priceLow"].ToString() + ";";
                    }
                    else
                    {
                        one = "";
                    }
                    if (currentPrice.priceHigh != Convert.ToInt32(model["priceHigh"].ToString()))
                    {
                        two = " Price (High) = " + currentPrice.priceHigh + " - " + model["priceHigh"].ToString() + ";";
                    }
                    else
                    {
                        two = "";
                    }
                    if (currentPrice.commodityRemarks != model["commodityRemarks"].ToString())
                    {
                        three = " Remarks = " + currentPrice.commodityRemarks + " - " + model["commodityRemarks"].ToString() + ";";
                    }
                    else
                    {
                        three = "";
                    }
                    var datas = one + two + three;
                    EditedDatas editedDatas = new EditedDatas
                    {
                        DateEdited = DateTime.Now,
                        Origin = "Price of commodities",
                        EditedBy = info.FullName,
                        ControlNumber = currentPrice.ControlNumber.Value
                    };
                    editedDatas.EditedData = datas;
                    editedDatas.Remarks = model["commodityRemarks"].ToString();
                    _context.EditedDatas.Add(editedDatas);
                }
                if (model["commodity"].ToString() != currentPrice.commodity)
                {
                    return Json(new { success = false, message = "Commodity cannot be changed!" });
                }
                if (model["classVariety"].ToString() != currentPrice.classVariety)
                {
                    return Json(new { success = false, message = "Class variety cannot be changed!" });
                }
                var check = _context.PriceCommodity.OrderByDescending(x => x.commodityDate).Where(x => x.commodity == model["commodity"].ToString() && x.classVariety == model["classVariety"].ToString()).Select(x => x.priceCommodityId).FirstOrDefault();
                if (check != currentPrice.priceCommodityId)
                {
                    return Json(new { success = false, message = "You are only allowed to change the latest datas!" });
                }
                var oldLowPrice = currentPrice.priceLow;
                var oldHighPrice = currentPrice.priceHigh;
                currentPrice.priceLow = Convert.ToDouble(model["priceLow"].ToString());
                currentPrice.priceHigh = Convert.ToDouble(model["priceHigh"].ToString());
                currentPrice.commodityRemarks = model["commodityRemarks"].ToString();
                currentPrice.averageLow = ((averageLow - oldLowPrice ) + currentPrice.priceLow) / currentPrice.totalDays;
                currentPrice.averageHigh = ((averageHigh - oldHighPrice) + currentPrice.priceHigh) / currentPrice.totalDays;
                currentPrice.enteredBy = info.FullName;
                _context.PriceCommodity.Update(currentPrice);
            }

            await _context.SaveChangesAsync();
            return Json(new { success = true, message = "Successfully Saved!" });
        }

        // DELETE: api/PriceCommodity/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeletePriceCommodity([FromRoute] Guid id)
        {
            PriceCommodity priceCommodity = _context.PriceCommodity.Where(x => x.priceCommodityId == id).FirstOrDefault();

src/src/Views/PriceCommodity/BarGraph.cshtml
@model src.Models.Organization
@{
    ViewData["Title"] = "Price Commodity";
    Layout = "_LayoutAdminltePriceCommodity";
}

<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    @*<div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <input type="hidden" asp-for="@Model.organizationId" />
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th class="col-md-11">Graph</th>
                                        <th class="col-md-1"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEdit","PriceCommodity", new { org = Model.organizationId })')"><i class="fa fa-plus"></i> Add New Graph</a>
                </div>
            </div>
        </div>
    </div>*@
    <div class="row">
        <div class="col-md-10">
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>

</section>
<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @*<script src="~/js/views/supportengineer/index.js"></script>*@
    <script src="~/lib/Graph/Chart.min.js"></script>
    <script>
        //$(document).ready(function () {

        function GetJSON_Simple() {
          var resp = [];
              $.ajax({
                  type: "GET",
                  url: '/PriceCommodity/BarGraph',
                  async: false,
                  contentType: "application/json",
                  success: function (data) {
                      resp.push(data);
                  },
                  error: function (req, status, error) {
                      // do something with error
                      alert("error");
                  }
              });
          return resp;
     }

        $(document).ready(function () {
            var simpleData = GetJSON_Simple();
            var ctx = document.getElementById('myChart');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    datasets: [{
                        label: '# of Votes',
                        //data: [12, 19, 3, 5, 2, 3],
                        data: simpleData,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });

    </script>
}

src/src/Views/PriceCommodity/Graph.cshtml
@model src.Models.Organization
@{
    ViewData["Title"] = "Price Commodity";
    Layout = "_LayoutAdminltePriceCommodity";
}

<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    @*<div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <input type="hidden" asp-for="@Model.organizationId" />
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th class="col-md-11">Graph</th>
                                        <th class="col-md-1"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEdit","PriceCommodity", new { org = Model.organizationId })')"><i class="fa fa-plus"></i> Add New Graph</a>
                </div>
            </div>
        </div>
    </div>*@
    <div class="row">
        <div class="col-md-10">
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>

</section>
<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @*<script src="~/js/views/supportengineer/index.js"></script>*@
    <script src="~/lib/Graph/Chart.min.js"></script>
    <script>
        //$(document).ready(function () {

        function GetJSON_Simple() {
            var resp = [];
            $.ajax({
                type: "GET",
                url: '/PriceCommodity/BarGraph',
                async: false,
                contentType: "application/json",
                success: function (data) {
                    resp.push(data);
                    //alert(resp);
                },
                error: function (req, status, error) {
                    // do something with error
                    alert("damn!");
                }
            });
            return resp;
        }

        $(document).ready(function () {
            var simpleData = GetJSON_Simple();
            var ctx = document.getElementById('myChart');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    datasets: [{
                        label: 'Commodities',
                        //data: simpleData,
                        data: [12, 19, 3, 5, 2, 3, 20, 18 ,9 , 12 , 6 ,2],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)',
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)',
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });


    </script>
}

src/src/Views/PriceCommodity/GraphMobile.cshtml
@model src.Models.Organization
@{
    ViewData["Title"] = "Price Commodity";
    Layout = "_LayoutAdminltePriceCommodity";
}

<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-lg-10">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <input type="hidden" asp-for="@Model.organizationId" />
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th class="col-md-11">Graph</th>
                                        <th class="col-md-1"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-2">
            <div class="row">
                <div class="col-md-12">
                    @*<a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEdit","PriceCommodity", new { org = Model.organizationId })')"><i class="fa fa-plus"></i> Add New Graph</a>*@
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>

</section>
<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @*<script src="~/js/views/supportengineer/index.js"></script>*@
    <script src="~/lib/Graph/Chart.min.js"></script>
    <script>
        //$(document).ready(function () {

        function GetJSON_Simple() {
          var resp = [];
              $.ajax({
                  type: "GET",
                  url: '/PriceCommodity/BarGraph',
                  async: false,
                  contentType: "application/json",
                  success: function (data) {
                      resp.push(data);
                  },
                  error: function (req, status, error) {
                      // do something with error
                      alert("error");
                  }
              });
          return resp;
     }

        $(document).ready(function () {
            var simpleData = GetJSON_Simple();
            var ctx = document.getElementById('myChart');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                    datasets: [{
                        label: '# of Votes',
                        //data: [12, 19, 3, 5, 2, 3],
                        data: simpleData,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });

    </script>
}

src/src/Views/PriceCommodity/Price.cshtml
@model src.Models.Organization
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Price Commodity";
    ApplicationUser appUser = await UserManager.GetUserAsync(User);
    Layout = "_LayoutAdminltePriceCommodity";
}

<!-- Content Header (Page header) -->
<!-- Main content -->
@if (appUser.isAdmin == false)
{
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEditPrice","PriceCommodity", new { org = Model.organizationId })')"><i class="fa fa-plus"></i> New price</a>
                                </div>
                                <input type="hidden" asp-for="@Model.organizationId" />
                                <table id="grid" name="grid" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            @*<th class="col-md-1">Class variety</th>*@
                                            <th class="col-md-1">Datetime</th>
                                            <th class="col-md-1">Commodity</th>
                                            <th class="col-md-1">Class variety</th>
                                            <th class="col-md-1">Price (Low)</th>
                                            <th class="col-md-1">Price (High)</th>
                                            <th class="col-md-1">Remarks</th>
                                            <th class="col-md-1">Control number</th>
                                            <th class="col-md-1">Entered by</th>
                                            @*<th class="col-md-1">Action</th>*@
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </section>
}
else
{
<section class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="col-md-6">
                                <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEditPrice","PriceCommodity", new { org = Model.organizationId })')"><i class="fa fa-plus"></i> New price</a>
                            </div>
                            <input type="hidden" asp-for="@Model.organizationId" />
                            <table id="grid" name="grid" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        @*<th class="col-md-1">Class variety</th>*@
                                        <th class="col-md-1">Datetime</th>
                                        <th class="col-md-1">Commodity</th>
                                        <th class="col-md-1">Class variety</th>
                                        <th class="col-md-1">Price (Low)</th>
                                        <th class="col-md-1">Price (High)</th>
                                        <th class="col-md-1">Price (Average)</th>
                                        <th class="col-md-1">Remarks</th>
                                        <th class="col-md-1">Control number</th>
                                        <th class="col-md-1">Entered by</th>
                                        <th class="col-md-1">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

</section>
}

<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @if (appUser.isAdmin == false)
    {
        <script src="~/js/views/priceCommodity/price.js"></script>
    }
    else if (appUser.isAdmin == true)
    {
        <script src="~/js/views/priceCommodity/priceIsAdmin.js"></script>
    }
}